before:
  hooks:
    - make test
builds:
  - id: polkaTax
    binary: polkaTax
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
    goos:
      - linux
      - darwin
      - windows
archives:
  - format: binary
    name_template: "{{ .Binary }}_{{ .Os }}"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
